sudo: false
language: node_js
node_js:
  - v9
  - v8
  - v6
after_success: codecov
after_script: codecov
notifications:
  email: false
  webhooks:
    on_success: change
    on_failure: always
    on_start: never
