language: node_js
node_js:
- '0.10'
after_script:
- npm run coveralls
- cat ./coverage/lcov.info | codeclimate
- rm -rf ./coverage
notifications:
  email:
    on_success: change
    on_failure: change
env:
  global:
    secure: IuI08EIR+WQtjNuqFrvxQ+iA5rstFUgZNf97y9UFLYOWZ8felBY1xdyyL1m7yM2mtmx61tv9cikz9XiGHleabbltQGGzExdmjA3IBUqUwg8hXwmThHTPDX7F+oB29sw4ICzf6k8IJfm6AjJg+B+72X/jDcm82U6NVO/vO33e3VY=
addons:
  code_climate:
    repo_token: 7b0cbee1382c968a036868d26ec04d0ddc7b7aeef25ceead5ff9ff50a3c2ae8b
