sudo: false
language: node_js
node_js:
  - 'node'
  - '7'
  - '6'
  - '5'
  - '4'
after_success: 'cat ./coverage/lcov.info | coveralls'
notifications:
  email: false
  webhooks:
    on_success: change
    on_failure: always
    on_start: never
