# Jekyll configuration precedence:
# 1. gulpfile
# 2. config.build.yml
# 3. config.yml

name: <%= projectname %>
description: <%= description %>
tagline: <%= tagline %>

# Used so Gulp knows where our app lives
source: 'src'
destination: 'serve'

owner:
  name: <%= ownerName %>
  email: <%= ownerEmail %>
  bio: <%= ownerBio %>
  twitter: <%= ownerTwitter %>

# general setting for Jekyll
googleAnalytics: UA-XXXXX-X

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true<% if (jekyllPageinate) { %>

permalink: <%= jekyllPermalinks %>
paginate: <%= jekyllPageinate %>
paginate_path: 'page:num'<% } %>

# Markdown library
markdown: redcarpet
# Markdown library options
# redcarpet:
  # extensions: ['fenced_code_blocks', 'smart']

pygments: true
